version: "3.7"

services:
  smart-brain-api:
    container_name: backend
    # image: node:12.1.0
    build: ./
    command: npm start
    working_dir: /usr/src/facerecognitionbrain_api/
    environment:
      POSTGRES_USER: chris
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/facerecognitionbrain_api

  # POSTGRES
  postgres:
    environment:
      POSTGRES_USER: chris
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"
