version: "3.7"

services:
  smart-brain-api:
    container_name: backend
    # image: node:12.1.0
    build: ./
    command: npm start
    working_dir: /usr/src/facerecognitionbrain_api/
    ports:
      - "3000:3000"
